name: Build Project & Commit
on:
  pull_request:
      types:
        - closed
jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Project
        uses: actions/setup-node@v3
        with:
          node-version: '12.x'
      - run: npm install
      - run: npm run build --if-present
      - name: Commit Changes
        uses: EndBug/add-and-commit@v9
        with:
          add: './dist -f'
          default_author: github_actor
          message: 'HubSpot Action: Build Project'
          pathspec_error_handling: exitImmediately
